/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dinopark;

import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author zsobe31
 */
public class Kifuto extends javax.swing.JFrame {

    /**
     * Creates new form Kifuto
     */
    public Kifuto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDinok = new javax.swing.JPanel();
        lstDinok = new javax.swing.JComboBox<>();
        pnlAdatok = new javax.swing.JPanel();
        txtNev = new javax.swing.JTextField();
        nbKor = new javax.swing.JSpinner();
        lblLany = new javax.swing.JLabel();
        btnMent = new javax.swing.JButton();
        lblKor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lstDinok.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", " ", " " }));
        lstDinok.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                lstDinokItemStateChanged(evt);
            }
        });

        pnlAdatok.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        btnMent.setText("Mentés");

        lblKor.setText("Kor:");

        javax.swing.GroupLayout pnlAdatokLayout = new javax.swing.GroupLayout(pnlAdatok);
        pnlAdatok.setLayout(pnlAdatokLayout);
        pnlAdatokLayout.setHorizontalGroup(
            pnlAdatokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdatokLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(txtNev, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblKor)
                .addGap(29, 29, 29)
                .addComponent(nbKor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(lblLany, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAdatokLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMent)
                .addGap(26, 26, 26))
        );
        pnlAdatokLayout.setVerticalGroup(
            pnlAdatokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdatokLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAdatokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nbKor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLany)
                    .addComponent(lblKor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(btnMent))
        );

        javax.swing.GroupLayout pnlDinokLayout = new javax.swing.GroupLayout(pnlDinok);
        pnlDinok.setLayout(pnlDinokLayout);
        pnlDinokLayout.setHorizontalGroup(
            pnlDinokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDinokLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lstDinok, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(pnlAdatok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlDinokLayout.setVerticalGroup(
            pnlDinokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDinokLayout.createSequentialGroup()
                .addGroup(pnlDinokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDinokLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(lstDinok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlDinokLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(pnlAdatok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlDinok, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlDinok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(254, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private List<Dino> ketrec = new ArrayList();
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        
        this.pnlAdatok.setVisible(false);
        
        Dino d = new Dino("Dani", 5, false);
        Dino i = new Dino("Zoe", 2, true);
        Dino n = new Dino("Joe", 9, false);
        Dino o = new Dino("Olga", 7, true);
        
        
        this.ketrec.add(d);
        this.ketrec.add(i);
        this.ketrec.add(n);
        this.ketrec.add(o);

        for( Dino allat : ketrec ){
            this.lstDinok.addItem(allat.nev);
        }

    }//GEN-LAST:event_formWindowOpened

    private void lstDinokItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_lstDinokItemStateChanged
        this.pnlAdatok.setVisible(true);
        int sorszam = this.lstDinok.getSelectedIndex();
        Dino kivalasztott = this.ketrec.get(sorszam);
        this.txtNev.setText(kivalasztott.nev);
        this.nbKor.setValue(kivalasztott.getKor());
        if( kivalasztott.lanyE() ){
            this.lblLany.setText("A kiválasztott dínó" + kivalasztott.nev + "lány");
        }
        else{
            this.lblLany.setText("A kiválasztott dínó" + kivalasztott.nev + "fiú");
        }
        
        
        
    }//GEN-LAST:event_lstDinokItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kifuto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kifuto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kifuto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kifuto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kifuto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMent;
    private javax.swing.JLabel lblKor;
    private javax.swing.JLabel lblLany;
    private javax.swing.JComboBox<String> lstDinok;
    private javax.swing.JSpinner nbKor;
    private javax.swing.JPanel pnlAdatok;
    private javax.swing.JPanel pnlDinok;
    private javax.swing.JTextField txtNev;
    // End of variables declaration//GEN-END:variables
}
